import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { AuthenticatedProtocol } from "../extensions/ephemeral-subagents/protocol.ts";
import { FallbackPolicyStore } from "../extensions/ephemeral-subagents/policy.ts";
import { SessionStore } from "../extensions/ephemeral-subagents/session.ts";
import { JobManager } from "../extensions/ephemeral-subagents/manager.ts";
import { selectBackend, type SandboxBackend, type SandboxRequest } from "../extensions/ephemeral-subagents/sandbox.ts";
import { WORKER_SOURCE } from "../extensions/ephemeral-subagents/worker.ts";
const exec=promisify(execFile);

async function repository(){const root=await mkdtemp(join(tmpdir(),"subagent-repo-"));await exec("git",["init",root]);await exec("git",["-C",root,"config","user.email","test@example.com"]);await exec("git",["-C",root,"config","user.name","Test"]);await writeFile(join(root,"a.txt"),"original\n");await exec("git",["-C",root,"add","."]);await exec("git",["-C",root,"commit","-m","initial"]);return root;}

test("authenticated protocol rejects malformed, duplicate and out-of-order frames",()=>{const p=new AuthenticatedProtocol("job","secret");const first=p.encode("status",1).trim();assert.equal(p.decode(first)?.type,"status");assert.equal(p.decode(first),undefined);assert.throws(()=>p.decode("nope"),/malformed/);assert.equal(p.decode(p.encode("late",3).trim())?.seq,3);assert.throws(()=>p.decode(p.encode("old",2).trim()),/out-of-order/);const tampered=JSON.parse(new AuthenticatedProtocol("job","bad").encode("x",4));assert.throws(()=>p.decode(JSON.stringify(tampered)),/authentication/);});

test("fallback policy is per-platform, persisted, and defaults to ask",async()=>{const dir=await mkdtemp(join(tmpdir(),"subagent-policy-"));const store=new FallbackPolicyStore(join(dir,"policy.json"));assert.equal(await store.get("linux"),"ask");await store.set("deny","linux");await store.set("allow","darwin");assert.equal(await store.get("linux"),"deny");assert.equal(await store.get("darwin"),"allow");assert.equal((await readFile(store.file,"utf8")).includes('"version": 1'),true);await rm(dir,{recursive:true});});

test("session creates disposable worktree and removal is idempotent",async()=>{const repo=await repository();const base=await mkdtemp(join(tmpdir(),"subagent-sessions-"));const store=new SessionStore(base);const s=await store.create(repo,"job");assert.equal(await readFile(join(s.worktree,"a.txt"),"utf8"),"original\n");await writeFile(join(s.worktree,"a.txt"),"changed\n");assert.equal(await readFile(join(repo,"a.txt"),"utf8"),"original\n");await store.remove(s);await store.remove(s);await rm(repo,{recursive:true,force:true});await rm(base,{recursive:true,force:true});});

test("backend selection prefers strength and does not silently choose none",async()=>{const backend=(id:string,strength:any,available:boolean):SandboxBackend=>({id,strength,async detect(){return{available,reason:"no"}},async plan(){throw new Error("unused")}});assert.equal((await selectBackend([backend("container","container",true),backend("native","native",true)])).backend?.id,"native");assert.equal((await selectBackend([backend("native","native",false)])).backend,undefined);});

class FakeBackend implements SandboxBackend {readonly id="fake";readonly strength="native" as const;private script:string;constructor(script:string){this.script=script;}async detect(){return{available:true}}async plan(r:SandboxRequest){return{command:process.execPath,args:["-e",WORKER_SOURCE,process.execPath,this.script],cwd:r.session.worktree,env:{PI_SUBAGENT_JOB_ID:r.control.jobId,PI_SUBAGENT_CONTROL_TOKEN:r.control.token},sandboxed:true,label:"fake",notices:[]}}}
class RetryStore extends SessionStore { attempts=0; override async remove(s:any){this.attempts++;if(this.attempts===1)throw new Error("busy");return super.remove(s);}}

test("manager runs concurrent jobs, captures results, and retries cleanup",async()=>{const repo=await repository();const dir=await mkdtemp(join(tmpdir(),"subagent-fake-"));const script=join(dir,"fake.mjs");await writeFile(script,`process.stdin.on('data',d=>{for(const l of d.toString().trim().split('\\n')){const c=JSON.parse(l);if(c.type==='prompt'){console.log(JSON.stringify({type:'message_update',assistantMessageEvent:{type:'text_delta',delta:'done'}}));console.log(JSON.stringify({type:'agent_settled'}));}}});`);const store=new RetryStore(join(dir,"sessions"));const m=new JobManager({repoRoot:repo,cwd:repo,limits:{concurrency:2,runtimeMs:5000},sessionStore:store,backends:[new FakeBackend(script)]});const h=m.launch([{task:"one"},{task:"two"}]);const results=await m.waitGroup(h.groupId);assert.deepEqual(results.map(r=>r.state),["completed","completed"]);assert.deepEqual(results.map(r=>r.output),["done","done"]);await new Promise(r=>setTimeout(r,1200));assert.equal(results.some(r=>r.cleanupPending),false);assert.ok(store.attempts>=3);await m.shutdown();await rm(repo,{recursive:true,force:true});await rm(dir,{recursive:true,force:true});});

test("queued cancellation is terminal and never starts",async()=>{const repo=await repository();const dir=await mkdtemp(join(tmpdir(),"subagent-cancel-"));const script=join(dir,"linger.mjs");await writeFile(script,`process.stdin.resume();setTimeout(()=>{},10000);`);const m=new JobManager({repoRoot:repo,cwd:repo,limits:{concurrency:1,runtimeMs:5000},sessionStore:new SessionStore(join(dir,"sessions")),backends:[new FakeBackend(script)]});const h=m.launch([{task:"running"},{task:"queued"}]);m.cancel(h.jobIds[1]);assert.equal((await m.wait(h.jobIds[1])).state,"cancelled");m.cancel(h.jobIds[0]);assert.equal((await m.wait(h.jobIds[0])).state,"cancelled");await m.shutdown();await rm(repo,{recursive:true,force:true});await rm(dir,{recursive:true,force:true});});

test("unsandboxed fallback requires consent and records saved-preference labeling",async()=>{const repo=await repository();const dir=await mkdtemp(join(tmpdir(),"subagent-consent-"));const script=join(dir,"fake.mjs");await writeFile(script,`process.stdin.on('data',d=>{for(const l of d.toString().trim().split('\\n'))if(JSON.parse(l).type==='prompt'){console.log(JSON.stringify({type:'agent_settled'}));}});`);
  let asked=0;const denied=new JobManager({repoRoot:repo,cwd:repo,piScript:script,backends:[],sessionStore:new SessionStore(join(dir,"denied")),allowUnsandboxed:async()=>{asked++;return false}});const d=denied.launch([{task:"x"}]);const dr=await denied.wait(d.jobIds[0]);assert.equal(asked,1);assert.equal(dr.state,"failed");assert.equal(dr.sandboxed,false);
  const allowed=new JobManager({repoRoot:repo,cwd:repo,piScript:script,backends:[],sessionStore:new SessionStore(join(dir,"allowed")),allowUnsandboxed:async()=>"saved preference"});const a=allowed.launch([{task:"x"}]);const ar=await allowed.wait(a.jobIds[0]);assert.equal(ar.state,"completed");assert.equal(ar.sandbox,"unsandboxed by saved preference");assert.equal(ar.sandboxed,false);await denied.shutdown();await allowed.shutdown();await rm(repo,{recursive:true,force:true});await rm(dir,{recursive:true,force:true});});
