import { randomBytes, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { realpath } from "node:fs/promises";
import type { JobEvent, JobRecord, JobResult, JobSpec, Limits, TerminalState } from "./types.ts";
import { DEFAULT_LIMITS, TERMINAL } from "./types.ts";
import { BubblewrapBackend, ContainerBackend, UnsandboxedBackend, selectBackend, type SandboxBackend } from "./sandbox.ts";
import { SessionStore } from "./session.ts";
import { AuthenticatedProtocol } from "./protocol.ts";

export interface ManagerOptions { repoRoot: string; cwd: string; limits?: Partial<Limits>; sessionStore?: SessionStore; backends?: SandboxBackend[]; allowUnsandboxed?: (spec: JobSpec, notices: string[]) => Promise<boolean | string>; piScript?: string; env?: NodeJS.ProcessEnv; defaultModel?: string; defaultProvider?: string; apiKey?: string; }
export class JobManager {
  readonly jobs = new Map<string, JobRecord>(); readonly groups = new Map<string, string[]>();
  readonly limits: Limits; private queue: string[] = []; private running = 0; private closing = false; private staleReaped = false; private readonly sessionStore: SessionStore; private protocols = new Map<string, AuthenticatedProtocol>(); private commandSeq = new Map<string, number>();
  private readonly options: ManagerOptions; constructor(options: ManagerOptions) { this.options=options; this.sessionStore=options.sessionStore ?? new SessionStore(); this.limits = { ...DEFAULT_LIMITS }; for (const [k,v] of Object.entries(options.limits ?? {})) if (v !== undefined) (this.limits as any)[k] = v; }
  private emit(j: JobRecord, type: string, data?: unknown) { const e: JobEvent = { seq: j.nextSeq++, at: new Date().toISOString(), type, ...(data === undefined ? {} : { data }) }; j.events.push(e); if (j.events.length > 1000) j.events.shift(); }
  launch(specs: JobSpec[]): { groupId: string; jobIds: string[] } {
    if (!specs.length) throw new Error("at least one task is required"); const groupId = randomUUID(); const ids: string[] = [];
    for (const spec of specs) { const id = randomUUID(); const j: JobRecord = { id, groupId, spec, state: "queued", createdAt: new Date().toISOString(), events: [], nextSeq: 1, output: "", stderr: "", truncated: false, settleWaiters: [], cancellationRequested: false, cleanupPending: false }; this.jobs.set(id,j); this.queue.push(id); ids.push(id); this.emit(j,"status",{state:"queued"}); }
    this.groups.set(groupId, ids); queueMicrotask(() => this.schedule()); return { groupId, jobIds: ids };
  }
  private schedule() { while (!this.closing && this.running < this.limits.concurrency && this.queue.length) { const id = this.queue.shift()!; const j = this.jobs.get(id); if (!j || j.state !== "queued") continue; this.running++; void this.start(j).finally(() => { this.running--; this.schedule(); }); } }
  private append(j: JobRecord, which: "output"|"stderr", text: string) { const room = this.limits.outputBytes - Buffer.byteLength(j.output+j.stderr); if (room <= 0) { j.truncated=true; return; } const b=Buffer.from(text); (j as any)[which] += b.subarray(0,room).toString("utf8"); if (b.length>room) j.truncated=true; }
  private async start(j: JobRecord) {
    try {
      if (j.cancellationRequested) return await this.finalize(j,"cancelled","cancelled while queued"); j.state="starting"; this.emit(j,"status",{state:j.state});
      const store=this.sessionStore; if(!this.staleReaped){this.staleReaped=true;const stale=await store.reapStale(this.options.repoRoot);if(stale.length)this.emit(j,"capability",`reaped ${stale.length} stale sessions`);} j.session=await store.create(this.options.repoRoot,j.id); const diskBytes=await store.diskUsage(j.session); if(diskBytes>this.limits.diskMb*1024*1024)throw new Error(`worktree exceeds disk limit (${diskBytes} > ${this.limits.diskMb*1024*1024} bytes)`); if (j.cancellationRequested) return await this.finalize(j,"cancelled","cancelled during startup");
      const selected=await selectBackend(this.options.backends ?? [new BubblewrapBackend(),new ContainerBackend()]); let backend=selected.backend;
      if (!backend) { const allowed=await this.options.allowUnsandboxed?.(j.spec,selected.notices) ?? false; if (!allowed) throw new Error(`No secure sandbox backend. ${selected.notices.join("; ")}`); backend=new UnsandboxedBackend(typeof allowed === "string" ? allowed : "explicit per-run confirmation"); }
      const script=this.options.piScript ?? await realpath(process.argv[1]); const args=["--mode","rpc","--no-session","--no-extensions","--no-skills","--no-prompt-templates","--no-context-files","--tools","read,bash,grep,find,ls"];
      if (j.spec.model) args.push("--model",j.spec.model); else if(this.options.defaultModel)args.push("--model",this.options.defaultModel); else if ((this.options.env ?? process.env).PI_MODEL) args.push("--model",(this.options.env ?? process.env).PI_MODEL!);
      if (!j.spec.model && this.options.defaultProvider) args.push("--provider",this.options.defaultProvider); else if (!j.spec.model && (this.options.env ?? process.env).PI_PROVIDER) args.push("--provider",(this.options.env ?? process.env).PI_PROVIDER!); if(this.options.apiKey)args.push("--api-key",this.options.apiKey);
      const token=randomBytes(32).toString("hex"); const protocol=new AuthenticatedProtocol(j.id,token); this.protocols.set(j.id,protocol); this.commandSeq.set(j.id,0); const plan=await backend.plan({session:j.session,cwd:this.options.cwd,piScript:script,piArgs:args,env:this.options.env ?? process.env,limits:this.limits,control:{jobId:j.id,token}}); j.backend=plan.label; j.sandboxed=plan.sandboxed; for(const n of [...selected.notices,...plan.notices]) this.emit(j,"capability",n);
      const child=spawn(plan.command,plan.args,{cwd:plan.cwd,env:plan.env,stdio:["pipe","pipe","pipe"],detached:true}); j.child=child; j.state="running"; j.startedAt=new Date().toISOString(); this.emit(j,"status",{state:j.state,backend:j.backend,sandboxed:j.sandboxed});
      let buffer=""; child.stdout!.on("data",d=>{ buffer+=d.toString(); for(;;){const n=buffer.indexOf("\n");if(n<0)break;const line=buffer.slice(0,n);buffer=buffer.slice(n+1);this.rpcEvent(j,line);} }); child.stderr!.on("data",d=>this.append(j,"stderr",d.toString()));
      child.on("error",e=>void this.finalize(j,"failed",`sandbox/runtime startup failed: ${e.message}`)); child.on("close",(code,signal)=>{if(!TERMINAL.has(j.state)) void this.finalize(j,j.cancellationRequested?"cancelled":"failed",j.cancellationRequested?"cancelled":`subagent crashed or control channel closed (${signal ?? code})`);});
      j.timer=setTimeout(()=>void this.finalize(j,"timed_out",`runtime exceeded ${this.limits.runtimeMs}ms`),this.limits.runtimeMs);
      this.sendRpc(j,{type:"prompt",id:"initial",message:`Investigate the repository read-only. Do not attempt to modify files. Return concise findings with file paths and line references.\n\nTask: ${j.spec.task}`});
      await this.wait(j.id);
    } catch(e) { if(!TERMINAL.has(j.state)) await this.finalize(j,j.cancellationRequested?"cancelled":"failed",e instanceof Error?e.message:String(e)); }
  }
  private rpcEvent(j:JobRecord,line:string){ let envelope; try{envelope=this.protocols.get(j.id)?.decode(line)}catch(e){this.emit(j,"protocol_error",String(e));return;} if(!envelope)return; if(envelope.type!=="rpc_event"){this.emit(j,envelope.type,envelope.payload);return;} const e:any=envelope.payload; this.emit(j,e.type??"event",e); if(e.type==="message_update"&&e.assistantMessageEvent?.type==="text_delta")this.append(j,"output",e.assistantMessageEvent.delta); if(e.type==="extension_ui_request"&&["select","confirm","input","editor"].includes(e.method)){j.state="needs_input";this.emit(j,"status",{state:j.state,request:e});} if(e.type==="agent_settled")void this.finalize(j,"completed","agent settled"); }
  private sendRpc(j:JobRecord,command:unknown){if(TERMINAL.has(j.state))throw new Error("job is terminal");if(!j.child?.stdin?.writable)throw new Error("control channel unavailable");const protocol=this.protocols.get(j.id);if(!protocol)throw new Error("control protocol unavailable");const seq=(this.commandSeq.get(j.id)??0)+1;this.commandSeq.set(j.id,seq);j.child.stdin.write(protocol.encode("rpc_command",seq,command));}
  message(id:string,text:string,followUp=false){const j=this.required(id);this.sendRpc(j,{type:followUp?"follow_up":"steer",message:text});this.emit(j,"message_sent",{followUp});}
  answer(id:string,requestId:string,value:unknown){const j=this.required(id);if(j.cancellationRequested)throw new Error("cancellation wins over late answers");this.sendRpc(j,{type:"extension_ui_response",id:requestId,...(typeof value==="boolean"?{confirmed:value}:{value})});j.state="running";}
  pause(id:string){const j=this.required(id);if(j.child?.pid)process.kill(-j.child.pid,"SIGSTOP");j.state="paused";this.emit(j,"status",{state:j.state});}
  resume(id:string){const j=this.required(id);if(j.state!=="paused")throw new Error("job is not paused");if(j.child?.pid)process.kill(-j.child.pid,"SIGCONT");j.state="running";this.emit(j,"status",{state:j.state});}
  cancel(id:string){const j=this.required(id);if(TERMINAL.has(j.state))return;j.cancellationRequested=true;this.queue=this.queue.filter(x=>x!==id);if(j.state==="starting")return;if(j.child){try{this.sendRpc(j,{type:"abort"});}catch{} this.killTree(j);}void this.finalize(j,"cancelled","cancelled by main agent");}
  private killTree(j:JobRecord){if(!j.child?.pid)return;try{process.kill(-j.child.pid,"SIGTERM")}catch{j.child.kill("SIGTERM")}setTimeout(()=>{if(!j.child?.pid)return;try{process.kill(-j.child.pid,"SIGKILL")}catch{}},1000).unref();}
  private async finalize(j:JobRecord,state:TerminalState,reason:string){if(j.result)return j.result; j.state=state;if(j.timer)clearTimeout(j.timer);this.killTree(j); const result:JobResult={jobId:j.id,groupId:j.groupId,state,terminalReason:reason,output:j.output,stderr:j.stderr,sandbox:j.backend??"none",sandboxed:j.sandboxed??false,startedAt:j.startedAt,finishedAt:new Date().toISOString(),truncated:j.truncated,cleanupPending:false};j.result=result;this.emit(j,"status",{state,reason}); if(j.session){try{await this.sessionStore.remove(j.session)}catch(e){j.cleanupPending=result.cleanupPending=true;this.emit(j,"cleanup_failed",String(e));setTimeout(()=>void this.retryCleanup(j),1000).unref();}} j.finalizationDone=true; for(const w of j.settleWaiters.splice(0))w(result);return result;}
  private async retryCleanup(j:JobRecord){if(!j.session||!j.cleanupPending)return;try{await this.sessionStore.remove(j.session);j.cleanupPending=j.result!.cleanupPending=false;this.emit(j,"cleanup_complete");}catch{setTimeout(()=>void this.retryCleanup(j),5000).unref();}}
  status(id:string){const j=this.required(id);return {id:j.id,groupId:j.groupId,state:j.state,backend:j.backend,sandboxed:j.sandboxed,events:j.events.slice(-20),result:j.result};}
  collect(id:string){return this.required(id).result;}
  wait(id:string):Promise<JobResult>{const j=this.required(id);return j.result && j.finalizationDone?Promise.resolve(j.result):new Promise(r=>j.settleWaiters.push(r));}
  waitGroup(groupId:string){const ids=this.groups.get(groupId);if(!ids)throw new Error("unknown group");return Promise.all(ids.map(id=>this.wait(id)));}
  private required(id:string){const j=this.jobs.get(id);if(!j)throw new Error(`unknown job: ${id}`);return j;}
  async shutdown(){this.closing=true;for(const j of this.jobs.values())if(!TERMINAL.has(j.state))this.cancel(j.id);await Promise.all([...this.jobs.values()].map(j=>this.wait(j.id)));}
}
